import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import AuthProvider from "./context/AuthProvider";
import { FirestoreProvider } from "./context/FirebaseProvider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

const materialSymbols = localFont({
  variable: "--font-family-symbols", // Variable name (to reference after in CSS/styles)
  style: "normal",
  src: "../../node_modules/material-symbols/material-symbols-rounded.woff2", // This is a reference to woff2 file from NPM package "material-symbols"
  display: "block",
  weight: "100 700",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* body height -> full height minus navbar height */}
      <body
        suppressHydrationWarning
        className={`${inter.className} ${materialSymbols.variable} h-[calc(100vh_-_5rem)]`}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <FirestoreProvider>
            <AuthProvider>
              <Navbar />
              {children}
            </AuthProvider>
          </FirestoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
